# Generated by Django 3.0.8 on 2020-07-13 21:03

from django.db import migrations, models
import django.db.models.deletion
import djangosite.portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='portfolio/projects/')),
                ('status', models.IntegerField(choices=[(0, 'On going'), (1, 'Completed')], default=0)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default=djangosite.portfolio.models.Category.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.Category')),
            ],
        ),
    ]
